# This file was generated by GoReleaser. DO NOT EDIT.
class Wsgnatsd < Formula
  desc "A websocket server proxy for nats-server"
  homepage "https://github.com/aricart/wsgnatsd"
  version "0.8.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/aricart/wsgnatsd/releases/download/v0.8.3/wsgnatsd-darwin-amd64.zip"
    sha256 "b161c2220adfd916fb0738f5a3a8cca10af87b7c08d9d136f7ea63ac19a4a78a"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/aricart/wsgnatsd/releases/download/v0.8.3/wsgnatsd-linux-amd64.zip"
      sha256 "e5ac5694fc3ab9c8d4621dd9d95be9715162fc9002b0ace045808ce33f6142b1"
    end
  end

  def install
    bin.install "wsgnatsd"
  end

  test do
    system "#{bin}/wsgnatsd --help"
  end
end
