# This file was generated by GoReleaser. DO NOT EDIT.
class Wsgnatsd < Formula
  desc "A websocket server proxy for nats-server"
  homepage "https://github.com/aricart/wsgnatsd"
  version "0.8.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/aricart/wsgnatsd/releases/download/v0.8.4/wsgnatsd-darwin-amd64.zip"
    sha256 "9b2e93b8434312c25da193b38a2fe7fffde3d6574015d75dcd81043eb39db4b8"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/aricart/wsgnatsd/releases/download/v0.8.4/wsgnatsd-linux-amd64.zip"
      sha256 "b5ba17f025e6f11cebf853a9e1c3c38ff4a1ae34bdccfb18a98ed70e2e00bcf3"
    end
  end

  def install
    bin.install "wsgnatsd"
  end

  test do
    system "#{bin}/wsgnatsd --help"
  end
end
